name: Update Playstore Apps

on:
  schedule:
    - cron: '0 */2 * 1-3 *'  # Every 2 hours on days 1-3 of every month
  workflow_dispatch:  # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: node index.js  # Assuming the code is saved as index.js
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add progress.json
          git commit -m "Update progress.json" || echo "No changes to commit"
          git push || echo "No changes to push"
